<?php require 'header.php' ?>

<div class="container">
  
  <h1>Page CONTACT</h1>
	<p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Incidunt minus quas assumenda eos vel ullam aut eaque veniam minima dolores nesciunt deleniti facere ab illum provident, sed sint perspiciatis? Eius.</p>
  <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Blanditiis, tempora reprehenderit. Quaerat unde, rerum, ab, debitis ea nulla molestiae neque laudantium exercitationem numquam adipisci dolorem natus blanditiis. Modi incidunt sapiente possimus! Molestias perferendis quibusdam similique, dicta ipsum consectetur minus sunt sed voluptatum qui ullam quam exercitationem quo omnis tempore impedit voluptas, laboriosam voluptate facilis. Illo expedita nisi pariatur rem voluptatibus labore quaerat minus consectetur voluptatem ipsum officiis exercitationem ullam, eveniet praesentium sequi quasi magnam nesciunt maxime nemo doloribus ut? Obcaecati libero, sapiente sit similique architecto quisquam aut nam sed deleniti minus asperiores impedit odit non totam? Doloribus fugiat praesentium iure asperiores labore saepe, vel molestiae cumque modi minima hic veniam tenetur distinctio facere, voluptate repellendus reiciendis aspernatur mollitia quibusdam corrupti expedita perspiciatis dignissimos ullam esse. Numquam sequi voluptatum dolor rem error quasi dolorem architecto amet illum deserunt voluptate repellendus ipsa enim similique voluptates animi perspiciatis incidunt eius modi, maiores repellat recusandae eum? Quas id perferendis sunt facere nulla iure sapiente itaque tenetur totam rem ratione commodi, provident aut numquam repellendus eius ducimus fugit minima quam necessitatibus dolores impedit odio? Voluptate a impedit sequi nihil praesentium natus. Natus cupiditate consequuntur ducimus laboriosam nobis id repudiandae suscipit in, vitae atque quidem molestias sint aliquam, saepe eos reprehenderit nulla voluptates! Aut accusamus ab blanditiis earum dignissimos officia id, omnis facilis aliquid rerum cumque ad architecto adipisci fugiat perspiciatis? Illum sapiente nobis, itaque harum necessitatibus excepturi beatae? Mollitia sunt nam iure unde eius explicabo harum culpa eligendi provident illum nobis ad dolore doloremque maiores fugit fuga, voluptatum sed adipisci vitae ipsam. Amet blanditiis veniam, consequuntur nam, voluptate a nostrum sint magnam debitis doloribus odit? Aliquid est minus neque voluptatum? Ipsum perferendis voluptatem minus, consequatur illum animi dignissimos earum vero corporis impedit reiciendis molestias ut molestiae temporibus, nemo sequi tempore? A ut earum pariatur asperiores!</p>
</div>

<?php require 'footer.php' ?>